### ISSUE TITLE
Pipeline fail at SNP construction and table conversion

### ISSUE THREAD

**Issue by retrorna** [IMSBCompBio/Halfpipe#1]
Hi all,

this is a really exciting pipeline, so I am trying to test it out. So far it goes pretty well but now I ran into an error that I don't know what it is pointing at.

I am runnin the pipeline as:

```
#!/bin/bash

#SBATCH --mem=50GB
#SBATCH -q long
#SBATCH --time=48:00:00
#SBATCH --job-name=halfpipe
#SBATCH --output=halfpipe.out
#SBATCH --cpus-per-task=10
#SBATCH --mail-user=ziga.vicic@imba.oeaw.ac.at
#SBATCH --mail-type=END

source ~/.bashrc
conda activate Halfpipe

python3 /Halfpipe/src/halfpipe.py pipe
```

This is my config:

```
---
 
input:
  samples: /HalfPipe/twocomp/samplesheet.tsv
  bed: /Halfpipe/annotations/3UTRs.bed
  refgenome: /Halfpipe/annotations/mm39.masked.fa
  snps: /Halfpipe/annotations/00-All.vcf
  summaryname: Test

output: /HalfPipe/twocomp/out/ # output directory

params:
  cores: 10 # number of cores for multi-processing
  gpus: null # if CUDA GPUs are available, specify number here
  readorientation: reverse # alternative: forward
  filterstrategy: pseudosingleend # alternative: singleend
  model: onecompartment # or choose 'twocompartment'

emparams:
  uridinethreshold: 30
  minimumcoverage: 100

...
```
This is the last update check pre-failure:

```
[UPDATE_CHECK] Your version of NGM is more than 6 months old - a newer version may be available. (For performing an automatic check use --update-check)
Detecting Editing Sites...
Creating Read Table for nuclearsample3_mapped_filtered.bam...
##### PRE-PROCESSING #####

Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...
Running NGM in paired-end mode...

```

And this is the error message:
```
INITIALIZING

CONSTRUCTING SNP AND CONVERSION TABLES ...
 done
Traceback (most recent call last):
  File "/Halfpipe/src/halfpipe.py", line 309, in <module>
    pipe() # run an grab a coffee
    ^^^^^^
  File "/Halfpipe/src/halfpipe.py", line 276, in pipe
    ReadPreProcess()
  File "/Halfpipe/src/halfpipe.py", line 189, in ReadPreProcess
    PreProcessReads(
  File "/Halfpipe/src/readpreprocessing.py", line 1135, in PreProcessReads
    create_editfile(
  File "/Halfpipe/src/readpreprocessing.py", line 1080, in create_editfile
    write_edit_sites(readtable, 0.05, editsites)
  File "/Halfpipe/src/readpreprocessing.py", line 977, in write_edit_sites
    rtable = load_read_table(rtable_file)  # loading read table
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Halfpipe/src/readpreprocessing.py", line 1037, in load_read_table
    gr = next(in_file).strip().split("#")[1]  # initialize current genomic region (first genomic region in file)
         ^^^^^^^^^^^^^
StopIteration
```

I do suspect it might have to do something with the SNP file I provided, because I never used those before and I downloaded it from https://ftp.ncbi.nih.gov/snp/organisms/archive/mouse_10090/

Second thing could be that I am supplying fastq as just demultiplexed files but not trimmed - it is not mentioned whether the pipeline does trimming or not.

Really hoping to resolve this! :)

Best,
Žiga
